add_executable(GamePadTouchTests GamePadTouchTests.cpp)
target_include_directories(GamePadTouchTests PRIVATE ../../src)
target_precompile_headers(GamePadTouchTests PRIVATE ../../src/Common/precompiled.h)
target_link_libraries(GamePadTouchTests PRIVATE pugixml::pugixml Boost::headers fmt::fmt glm::glm)
set_property(TARGET GamePadTouchTests PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
add_test(NAME GamePadTouch COMMAND GamePadTouchTests)

add_executable(GamePadTouchIntegrationTests GamePadTouchIntegrationTests.cpp)
target_link_libraries(GamePadTouchIntegrationTests PRIVATE CemuInput CemuCommon glm::glm pugixml::pugixml SDL2::SDL2 wx::base wx::core)
if (ENABLE_HIDAPI)
	target_link_libraries(GamePadTouchIntegrationTests PRIVATE hidapi::hidapi)
endif()
if (WIN32)
	target_link_libraries(GamePadTouchIntegrationTests PRIVATE Dbghelp)
endif()
set_property(TARGET GamePadTouchIntegrationTests PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
add_test(NAME GamePadTouchIntegration COMMAND GamePadTouchIntegrationTests)
