blank_issues_enabled: false
contact_links:
  - name: Cemu Discord
    url: https://discord.com/invite/5psYsup
    about: If you need technical support with Cemu or have other questions the best place to ask is on the official Cemu Discord linked here
