blank_issues_enabled: false
contact_links:
  - name: Cemu Discord
    url: https://discord.com/invite/5psYsup
    about: If you are experiencing an issue with Cemu, and you need tech support, or if you have a general question, try asking in the official Cemu Discord linked here. Piracy is not allowed.
