# Docs - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Bug Report
description: Report an issue with Cemu emulator
title: "Enter a title for the bug report here"
labels: bug
body:
  - type: markdown
    id: md_readme
    attributes:
      value: |
        ## Important: Read First
        
        If you discovered a bug you can report it here. Please make sure of the following first:
        - That you are using the latest version of Cemu
        - Only report something if you are sure it's a bug and not any technical issue on your end. For troubleshooting help see the [links page](https://github.com/cemu-project/Cemu#links)
        - Problems specific to a single game should be reported on the [compatibility wiki](https://wiki.cemu.info/wiki/Main_Page) instead
        - Verify that your problem isn't already mentioned on the [issue tracker](https://github.com/cemu-project/Cemu/issues)
        
        Additionally, be aware that graphic packs can also causes issues. There is a separate issue tracker for graphic pack bugs over at the [graphic pack repository](https://github.com/cemu-project/cemu_graphic_packs)
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: "What the bug is, in a brief description"
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: "How to reproduce the issue"
    validations:
      required: true
  - type: textarea
    id: sys_info
    attributes:
      label: System Info (Optional)
      description: "Your PC specifications. Usually only the operating system and graphics card is important. But feel free to add more info."
      placeholder: |
        Info        
        OS: Windows 10
        GPU: NVIDIA GeForce RTX 4090
      value: |
        OS: 
        GPU: 
  - type: textarea
    id: emulation_settings
    attributes:
      label: Emulation Settings (Optional)
      description: |
        Any non-default settings. You can leave this empty if you didn't change anything other than input settings.
    validations:
      required: false
  - type: textarea
    id: logs_files
    attributes:
      label: "Logs (Optional)"
      description: |
        "Attach `log.txt` from your Cemu folder (*File > Open Cemu folder*)".
    validations:
      required: false
