name: Lint

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "*.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: './src'
          clangFormatVersion: 14
